In [1]:
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
from tensorflow.keras.optimizers import Adam

In [2]:
x = []
y = []
for i in range(1000):
    a = np.random.randint(0,60)
    x.append(a)
    y.append(0)
    b = np.random.randint(61,100)
    x.append(b)
    y.append(1)

In [3]:
x = np.array(x)
y = np.array(y)

In [4]:
x_org = x
y_org = y

In [5]:
x = x_org

In [6]:
x = x.reshape(-1,1)

In [7]:
y_list = list(y)

In [8]:
scaler = MinMaxScaler(feature_range=(0,1))

In [9]:
scaler = scaler.fit(x)

In [10]:
x = scaler.transform(x)

In [11]:
x

array([[0.21212121],
       [0.83838384],
       [0.04040404],
       ...,
       [0.86868687],
       [0.38383838],
       [0.6969697 ]])

In [12]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

In [13]:
model = keras.Sequential(
    [
        layers.Dense(16, input_shape=(1,), activation="relu"),
        layers.Dense(32, activation="relu", name='XXXX'),
        layers.Dense(2, activation="softmax"),
    ]
)

In [14]:
model.compile(loss='sparse_categorical_crossentropy',metrics=['accuracy'],optimizer=Adam(learning_rate=0.0001))

In [15]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 16)                32        
_________________________________________________________________
XXXX (Dense)                 (None, 32)                544       
_________________________________________________________________
dense_1 (Dense)              (None, 2)                 66        
Total params: 642
Trainable params: 642
Non-trainable params: 0
_________________________________________________________________


In [16]:
model.fit(x_train, y_train, epochs=60, shuffle=True, batch_size=30, verbose=2 ,validation_split=0.1)

Epoch 1/60
48/48 - 2s - loss: 0.6992 - accuracy: 0.4618 - val_loss: 0.6948 - val_accuracy: 0.3688
Epoch 2/60
48/48 - 0s - loss: 0.6905 - accuracy: 0.5514 - val_loss: 0.6862 - val_accuracy: 0.6313
Epoch 3/60
48/48 - 0s - loss: 0.6804 - accuracy: 0.6396 - val_loss: 0.6767 - val_accuracy: 0.6500
Epoch 4/60
48/48 - 0s - loss: 0.6716 - accuracy: 0.6681 - val_loss: 0.6689 - val_accuracy: 0.6687
Epoch 5/60
48/48 - 0s - loss: 0.6628 - accuracy: 0.7021 - val_loss: 0.6608 - val_accuracy: 0.6875
Epoch 6/60
48/48 - 0s - loss: 0.6533 - accuracy: 0.7250 - val_loss: 0.6518 - val_accuracy: 0.6938
Epoch 7/60
48/48 - 0s - loss: 0.6445 - accuracy: 0.7285 - val_loss: 0.6443 - val_accuracy: 0.6938
Epoch 8/60
48/48 - 0s - loss: 0.6365 - accuracy: 0.7410 - val_loss: 0.6370 - val_accuracy: 0.6938
Epoch 9/60
48/48 - 0s - loss: 0.6283 - accuracy: 0.7451 - val_loss: 0.6293 - val_accuracy: 0.6938
Epoch 10/60
48/48 - 0s - loss: 0.6200 - accuracy: 0.7535 - val_loss: 0.6218 - val_accuracy: 0.7000
Epoch 11/60
48/48 -

In [17]:
predictions = model.predict(x_test, batch_size=10)

In [18]:
for i in predictions:
    print(i)

[0.8380073 0.1619927]
[0.12883544 0.87116456]
[0.13737838 0.8626216 ]
[0.12883544 0.87116456]
[0.07600821 0.92399174]
[0.06252059 0.93747944]
[0.914575   0.08542505]
[0.2791776 0.7208224]
[0.06252059 0.93747944]
[0.06252059 0.93747944]
[0.5404914 0.4595086]
[0.9172407  0.08275933]
[0.8380073 0.1619927]
[0.8897139  0.11028611]
[0.9140326  0.08596744]
[0.08661841 0.9133816 ]
[0.64718026 0.35281977]
[0.558821   0.44117892]
[0.91892225 0.08107774]
[0.44819474 0.5518053 ]
[0.8168815  0.18311855]
[0.8897139  0.11028611]
[0.08106757 0.91893244]
[0.19894668 0.80105335]
[0.64718026 0.35281977]
[0.18740685 0.81259316]
[0.11310494 0.88689506]
[0.89677376 0.1032263 ]
[0.913487   0.08651295]
[0.34246835 0.6575317 ]
[0.42995733 0.57004267]
[0.89677376 0.1032263 ]
[0.48504138 0.5149586 ]
[0.06252059 0.93747944]
[0.5035513  0.49644873]
[0.74096954 0.25903043]
[0.11310494 0.88689506]
[0.865954 0.134046]
[0.68022    0.31978002]
[0.88223463 0.11776533]
[0.558821   0.44117892]
[0.37655452 0.62344545]
[0.2

In [19]:
new_preds = np.argmax(predictions, axis=0)

In [20]:
for i in new_preds:
    print(i)

142
269


In [21]:
predictions[13,0]

0.8897139

In [22]:
predictions[70,1]

0.88689506

In [23]:
max = 0
for i in predictions[:,0]:
    if i > max:
        max = i
print(max)

0.9197975


In [24]:
max = 0
for i in predictions[:,1]:
    if i > max:
        max = i
print(max)

0.9527139


In [25]:
a = tf.Variable(7)

In [26]:
a

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=7>

In [27]:
b = tf.Variable(8)

In [28]:
b

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=8>

In [34]:
first_weights = model.get_weights()

In [37]:
np.savez('Output_Weights.txt', first_weights ,fmt='%s')

In [38]:
#model.save and #load_model (copies entire model)

In [40]:
#model.to_json and #model_from_json (copies only architecture)

In [41]:
first_weights

[array([[-0.41148782,  0.8101519 , -0.20500746,  0.85799515, -0.45918357,
         -0.38480705, -0.26736593,  0.18511297, -0.4512539 , -0.01296687,
         -0.46584386, -0.00716764,  0.79747903, -0.02686828, -0.3640826 ,
         -0.35984838]], dtype=float32),
 array([ 0.        ,  0.14020148,  0.        , -0.18890677,  0.        ,
         0.        ,  0.        ,  0.23948736,  0.        ,  0.        ,
         0.        ,  0.        , -0.16813855,  0.        ,  0.        ,
         0.        ], dtype=float32),
 array([[-4.23583388e-02, -2.96940148e-01,  2.17669576e-01,
         -1.84789225e-01,  6.86343014e-02, -7.32437074e-02,
         -3.16123456e-01,  3.20953459e-01,  2.16895491e-01,
          8.19175541e-02, -3.25477600e-01, -4.55056131e-02,
         -1.69985235e-01,  2.08765835e-01,  2.02243656e-01,
         -3.29824209e-01, -1.54853076e-01,  3.26365829e-02,
          3.23919266e-01,  7.37514198e-02, -3.23426992e-01,
         -3.37264121e-01, -2.71548867e-01,  2.26394922e-01,
 

In [60]:
model_vgg = tf.keras.applications.vgg16.VGG16()

553467904/553467096 [==============================] - 647s 1us/step


In [65]:
model_vgg.dtype

'float32'

In [64]:
type(model_vgg)

tensorflow.python.keras.engine.functional.Functional

In [66]:
type(model)

tensorflow.python.keras.engine.sequential.Sequential

In [68]:
my_vgg = keras.Sequential()

In [70]:
for layer in model_vgg.layers[:-1]:
    my_vgg.add(layer)

In [71]:
my_vgg.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
block1_conv1 (Conv2D)        (None, 224, 224, 64)      1792      
_________________________________________________________________
block1_conv2 (Conv2D)        (None, 224, 224, 64)      36928     
_________________________________________________________________
block1_pool (MaxPooling2D)   (None, 112, 112, 64)      0         
_________________________________________________________________
block2_conv1 (Conv2D)        (None, 112, 112, 128)     73856     
_________________________________________________________________
block2_conv2 (Conv2D)        (None, 112, 112, 128)     147584    
_________________________________________________________________
block2_pool (MaxPooling2D)   (None, 56, 56, 128)       0         
_________________________________________________________________
block3_conv1 (Conv2D)        (None, 56, 56, 256)      

In [73]:
my_vgg.add(layers.Dense(2, activation='softmax'))

In [77]:
for layer in my_vgg.layers[:-1]:
    layer.trainable = False

In [84]:
a = np.arange(1,25)

In [80]:
a = list(a)

In [86]:
a[-6].output

AttributeError: 'numpy.int32' object has no attribute 'output'

In [76]:
my_vgg.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
block1_conv1 (Conv2D)        (None, 224, 224, 64)      1792      
_________________________________________________________________
block1_conv2 (Conv2D)        (None, 224, 224, 64)      36928     
_________________________________________________________________
block1_pool (MaxPooling2D)   (None, 112, 112, 64)      0         
_________________________________________________________________
block2_conv1 (Conv2D)        (None, 112, 112, 128)     73856     
_________________________________________________________________
block2_conv2 (Conv2D)        (None, 112, 112, 128)     147584    
_________________________________________________________________
block2_pool (MaxPooling2D)   (None, 56, 56, 128)       0         
_________________________________________________________________
block3_conv1 (Conv2D)        (None, 56, 56, 256)      

In [67]:
model_vgg.summary()

Model: "vgg16"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_1 (InputLayer)         [(None, 224, 224, 3)]     0         
_________________________________________________________________
block1_conv1 (Conv2D)        (None, 224, 224, 64)      1792      
_________________________________________________________________
block1_conv2 (Conv2D)        (None, 224, 224, 64)      36928     
_________________________________________________________________
block1_pool (MaxPooling2D)   (None, 112, 112, 64)      0         
_________________________________________________________________
block2_conv1 (Conv2D)        (None, 112, 112, 128)     73856     
_________________________________________________________________
block2_conv2 (Conv2D)        (None, 112, 112, 128)     147584    
_________________________________________________________________
block2_pool (MaxPooling2D)   (None, 56, 56, 128)       0     

In [56]:
a = 0
for i in first_weights:
    b = (len(i.reshape(-1)))
    a+=b
print(a)
    

642
