In [1]:
import numpy as np

In [2]:
x = []
y = []
for i in range(100):
    a = np.random.randint(0,60)
    x.append(a)
    y.append(0)
    b = np.random.randint(61,100)
    x.append(b)
    y.append(1)

In [6]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split

In [17]:
x = np.array(x)
y = np.array(y)

In [18]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

In [19]:
clf = LogisticRegression()
clf.fit(x_train.reshape(-1,1), y_train)

LogisticRegression()

In [22]:
predict = clf.predict(x_test.reshape(-1,1))

In [23]:
import pandas as pd

In [26]:
pd.DataFrame({'Predict': predict, 'Actual':y_test})

Predict  Actual
0         1       1
1         1       1
2         0       0
3         0       0
4         0       0
5         1       1
6         1       1
7         0       0
8         0       0
9         1       1
10        0       0
11        0       0
12        1       1
13        0       0
14        0       0
15        1       1
16        0       0
17        0       0
18        0       0
19        0       0
20        0       0
21        0       0
22        0       0
23        1       1
24        1       1
25        0       0
26        0       0
27        1       1
28        1       1
29        0       0
30        1       1
31        0       0
32        1       1
33        1       1
34        0       0
35        0       0
36        1       1
37        1       1
38        0       0
39        0       0

In [28]:
clf.score(x_test.reshape(-1,1), y_test)

1.0

In [30]:
clf.predict([[13]])

array([0])

In [31]:
clf.predict([[78]])

array([1])

In [35]:
clf.predict(np.array(13).reshape(-1,1))

array([0])