In [1]:
import numpy as np

In [2]:
import pandas as pd

In [5]:
a = np.random.randint(1,100,size=(75))
b = np.random.randint(1,100,size=(75))
c = np.random.randint(1,100,size=(75))

In [23]:
d = 3*a + 1.5*b -4*c +100

In [24]:
df = pd.DataFrame({'A':a, 'B':b, 'C':c, 'D':d})

In [25]:
df

A   B   C      D
0   99  50  94   96.0
1   77  15  70   73.5
2   83  56  10  393.0
3   27  51  23  165.5
4   29  19  36   71.5
..  ..  ..  ..    ...
70  45   7  44   69.5
71  84  46  81   97.0
72  73  85  98   54.5
73  95  68   1  483.0
74  83  91  12  437.5

[75 rows x 4 columns]

In [26]:
from sklearn.linear_model import LinearRegression

In [27]:
reg = LinearRegression()

In [28]:
x = df.drop(['D'], axis=1)
y = df['D']

In [29]:
reg.fit(x,y)

LinearRegression()

In [30]:
reg.coef_

array([ 3. ,  1.5, -4. ])

In [31]:
reg.intercept_

100.00000000000013

# Lets try with NN

In [33]:
import tensorflow as tf

In [34]:
model = tf.keras.models.Sequential()

In [35]:
x.shape

(75, 3)

In [40]:
model.add(tf.keras.layers.Dense(10, input_shape=(3,)))

In [41]:
model.add(tf.keras.layers.Dense(32, activation='relu'))

In [42]:
model.add(tf.keras.layers.Dense(1, activation='linear'))

In [43]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_1 (Dense)              (None, 10)                40        
_________________________________________________________________
dense_2 (Dense)              (None, 32)                352       
_________________________________________________________________
dense_3 (Dense)              (None, 1)                 33        
Total params: 425
Trainable params: 425
Non-trainable params: 0
_________________________________________________________________


In [44]:
model.get_weights()

[array([[ 0.0821107 ,  0.6239157 ,  0.11105973,  0.54596746, -0.00965279,
         -0.62067497,  0.17786008, -0.06201369, -0.21511754, -0.45268363],
        [ 0.21334147, -0.15844673, -0.03765029,  0.23887241, -0.11073226,
          0.25821656, -0.51371443,  0.1337626 ,  0.01905441, -0.07772917],
        [-0.45122603, -0.3752287 ,  0.02720785, -0.5650842 , -0.2763858 ,
          0.2890557 , -0.3321533 , -0.65904146, -0.05914223,  0.17534786]],
       dtype=float32),
 array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32),
 array([[ 0.2207047 , -0.29660544, -0.20024619, -0.34325904, -0.09785208,
         -0.01581028, -0.31227064, -0.23068066,  0.02097425, -0.14443116,
          0.22286645,  0.30594072, -0.11872947, -0.2108724 ,  0.03343022,
         -0.18116947, -0.13711321, -0.30033398,  0.25030896, -0.19714014,
         -0.16125315,  0.3480741 , -0.29206696,  0.3344213 , -0.31092623,
         -0.23424962, -0.15526456,  0.27110842, -0.28316084, -0.14776853,
          0.24785623

In [47]:
from sklearn.model_selection import train_test_split

In [48]:
X = x

In [49]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [57]:
mea = tf.keras.losses.MeanSquaredError(reduction="auto", name="mean_squared_error")

In [59]:
model.compile(loss='mean_squared_error', metrics= [mea], optimizer='adam')

In [60]:
model.fit(X_train, y_train, epochs=500, shuffle=True, validation_split=0.1, batch_size=10)

Epoch 1/500
5/5 [==============================] - 1s 64ms/step - loss: 365.8549 - mean_squared_error: 360.6604 - val_loss: 854.1805 - val_mean_squared_error: 854.1805
Epoch 2/500
5/5 [==============================] - 0s 14ms/step - loss: 356.3495 - mean_squared_error: 363.5522 - val_loss: 926.3856 - val_mean_squared_error: 926.3856
Epoch 3/500
5/5 [==============================] - 0s 18ms/step - loss: 348.4053 - mean_squared_error: 338.1747 - val_loss: 941.2770 - val_mean_squared_error: 941.2770
Epoch 4/500
5/5 [==============================] - 0s 20ms/step - loss: 345.3340 - mean_squared_error: 333.1686 - val_loss: 969.6606 - val_mean_squared_error: 969.6606
Epoch 5/500
5/5 [==============================] - 0s 15ms/step - loss: 332.9976 - mean_squared_error: 366.5753 - val_loss: 964.5532 - val_mean_squared_error: 964.5532
Epoch 6/500
5/5 [==============================] - 0s 13ms/step - loss: 335.0569 - mean_squared_error: 336.8513 - val_loss: 961.4764 - val_mean_squared_error: 9

5/5 [==============================] - 0s 11ms/step - loss: 281.1511 - mean_squared_error: 271.8658 - val_loss: 848.8302 - val_mean_squared_error: 848.8302
Epoch 50/500
5/5 [==============================] - 0s 10ms/step - loss: 278.8961 - mean_squared_error: 270.4059 - val_loss: 858.4287 - val_mean_squared_error: 858.4287
Epoch 51/500
5/5 [==============================] - 0s 10ms/step - loss: 278.4306 - mean_squared_error: 270.5028 - val_loss: 876.6876 - val_mean_squared_error: 876.6876
Epoch 52/500
5/5 [==============================] - 0s 9ms/step - loss: 275.4652 - mean_squared_error: 282.5445 - val_loss: 900.4810 - val_mean_squared_error: 900.4810
Epoch 53/500
5/5 [==============================] - 0s 10ms/step - loss: 274.3854 - mean_squared_error: 277.4341 - val_loss: 917.2936 - val_mean_squared_error: 917.2936
Epoch 54/500
5/5 [==============================] - 0s 9ms/step - loss: 273.7427 - mean_squared_error: 256.5357 - val_loss: 942.9518 - val_mean_squared_error: 942.9518
E

Epoch 98/500
5/5 [==============================] - 0s 10ms/step - loss: 231.8262 - mean_squared_error: 257.9408 - val_loss: 854.8984 - val_mean_squared_error: 854.8984
Epoch 99/500
5/5 [==============================] - 0s 11ms/step - loss: 227.4077 - mean_squared_error: 212.3037 - val_loss: 869.8533 - val_mean_squared_error: 869.8533
Epoch 100/500
5/5 [==============================] - 0s 13ms/step - loss: 226.7962 - mean_squared_error: 214.5694 - val_loss: 853.5132 - val_mean_squared_error: 853.5132
Epoch 101/500
5/5 [==============================] - 0s 12ms/step - loss: 227.2125 - mean_squared_error: 222.6260 - val_loss: 878.2684 - val_mean_squared_error: 878.2684
Epoch 102/500
5/5 [==============================] - 0s 11ms/step - loss: 224.8487 - mean_squared_error: 231.4515 - val_loss: 842.5640 - val_mean_squared_error: 842.5640
Epoch 103/500
5/5 [==============================] - 0s 11ms/step - loss: 228.5049 - mean_squared_error: 278.1795 - val_loss: 821.0217 - val_mean_square

5/5 [==============================] - 0s 13ms/step - loss: 197.7561 - mean_squared_error: 183.8429 - val_loss: 864.8464 - val_mean_squared_error: 864.8464
Epoch 147/500
5/5 [==============================] - 0s 11ms/step - loss: 193.7849 - mean_squared_error: 201.4079 - val_loss: 845.7750 - val_mean_squared_error: 845.7750
Epoch 148/500
5/5 [==============================] - 0s 11ms/step - loss: 194.1055 - mean_squared_error: 199.9519 - val_loss: 832.6761 - val_mean_squared_error: 832.6761
Epoch 149/500
5/5 [==============================] - 0s 10ms/step - loss: 195.7542 - mean_squared_error: 186.2771 - val_loss: 829.7204 - val_mean_squared_error: 829.7204
Epoch 150/500
5/5 [==============================] - 0s 10ms/step - loss: 194.4509 - mean_squared_error: 185.5543 - val_loss: 803.6699 - val_mean_squared_error: 803.6699
Epoch 151/500
5/5 [==============================] - 0s 12ms/step - loss: 194.7405 - mean_squared_error: 181.5669 - val_loss: 802.8537 - val_mean_squared_error: 802

5/5 [==============================] - 0s 11ms/step - loss: 170.6708 - mean_squared_error: 164.2619 - val_loss: 807.8723 - val_mean_squared_error: 807.8723
Epoch 195/500
5/5 [==============================] - 0s 10ms/step - loss: 168.5052 - mean_squared_error: 163.2926 - val_loss: 813.6181 - val_mean_squared_error: 813.6181
Epoch 196/500
5/5 [==============================] - 0s 10ms/step - loss: 169.3059 - mean_squared_error: 153.8928 - val_loss: 806.1283 - val_mean_squared_error: 806.1283
Epoch 197/500
5/5 [==============================] - 0s 9ms/step - loss: 168.2323 - mean_squared_error: 160.6117 - val_loss: 799.1157 - val_mean_squared_error: 799.1157
Epoch 198/500
5/5 [==============================] - 0s 11ms/step - loss: 166.3944 - mean_squared_error: 156.3526 - val_loss: 824.0601 - val_mean_squared_error: 824.0601
Epoch 199/500
5/5 [==============================] - 0s 11ms/step - loss: 171.1539 - mean_squared_error: 168.0241 - val_loss: 826.4095 - val_mean_squared_error: 826.

5/5 [==============================] - 0s 10ms/step - loss: 144.9425 - mean_squared_error: 142.3072 - val_loss: 725.5742 - val_mean_squared_error: 725.5742
Epoch 243/500
5/5 [==============================] - 0s 10ms/step - loss: 145.4072 - mean_squared_error: 169.7781 - val_loss: 736.8519 - val_mean_squared_error: 736.8519
Epoch 244/500
5/5 [==============================] - 0s 9ms/step - loss: 142.3989 - mean_squared_error: 132.5210 - val_loss: 753.0993 - val_mean_squared_error: 753.0993
Epoch 245/500
5/5 [==============================] - 0s 10ms/step - loss: 145.9461 - mean_squared_error: 155.5768 - val_loss: 759.9412 - val_mean_squared_error: 759.9412
Epoch 246/500
5/5 [==============================] - 0s 8ms/step - loss: 143.1801 - mean_squared_error: 139.2288 - val_loss: 708.7681 - val_mean_squared_error: 708.7681
Epoch 247/500
5/5 [==============================] - 0s 12ms/step - loss: 141.7633 - mean_squared_error: 139.5998 - val_loss: 732.9177 - val_mean_squared_error: 732.9

5/5 [==============================] - 0s 10ms/step - loss: 121.7351 - mean_squared_error: 117.3545 - val_loss: 701.9205 - val_mean_squared_error: 701.9205
Epoch 291/500
5/5 [==============================] - 0s 10ms/step - loss: 122.4931 - mean_squared_error: 117.2428 - val_loss: 693.4823 - val_mean_squared_error: 693.4823
Epoch 292/500
5/5 [==============================] - 0s 10ms/step - loss: 123.6926 - mean_squared_error: 122.0761 - val_loss: 700.2482 - val_mean_squared_error: 700.2482
Epoch 293/500
5/5 [==============================] - 0s 9ms/step - loss: 119.4451 - mean_squared_error: 112.9049 - val_loss: 676.1703 - val_mean_squared_error: 676.1703
Epoch 294/500
5/5 [==============================] - 0s 10ms/step - loss: 120.1700 - mean_squared_error: 110.2797 - val_loss: 659.0077 - val_mean_squared_error: 659.0077
Epoch 295/500
5/5 [==============================] - 0s 11ms/step - loss: 122.2604 - mean_squared_error: 148.5432 - val_loss: 679.3022 - val_mean_squared_error: 679.

5/5 [==============================] - 0s 10ms/step - loss: 102.2261 - mean_squared_error: 96.8751 - val_loss: 626.9891 - val_mean_squared_error: 626.9891
Epoch 339/500
5/5 [==============================] - 0s 10ms/step - loss: 102.5593 - mean_squared_error: 99.6858 - val_loss: 572.9614 - val_mean_squared_error: 572.9614
Epoch 340/500
5/5 [==============================] - 0s 9ms/step - loss: 97.3739 - mean_squared_error: 95.5032 - val_loss: 592.0216 - val_mean_squared_error: 592.0216
Epoch 341/500
5/5 [==============================] - 0s 11ms/step - loss: 98.5909 - mean_squared_error: 99.7517 - val_loss: 599.8220 - val_mean_squared_error: 599.8220
Epoch 342/500
5/5 [==============================] - 0s 16ms/step - loss: 101.8322 - mean_squared_error: 100.3221 - val_loss: 555.7885 - val_mean_squared_error: 555.7885
Epoch 343/500
5/5 [==============================] - 0s 10ms/step - loss: 99.0803 - mean_squared_error: 96.4974 - val_loss: 613.8657 - val_mean_squared_error: 613.8657
Epo

Epoch 387/500
5/5 [==============================] - 0s 9ms/step - loss: 81.6594 - mean_squared_error: 82.7545 - val_loss: 545.4033 - val_mean_squared_error: 545.4033
Epoch 388/500
5/5 [==============================] - 0s 11ms/step - loss: 77.8889 - mean_squared_error: 75.7484 - val_loss: 518.6977 - val_mean_squared_error: 518.6977
Epoch 389/500
5/5 [==============================] - 0s 10ms/step - loss: 78.5725 - mean_squared_error: 86.5377 - val_loss: 498.1920 - val_mean_squared_error: 498.1920
Epoch 390/500
5/5 [==============================] - 0s 12ms/step - loss: 79.9412 - mean_squared_error: 76.8027 - val_loss: 503.5091 - val_mean_squared_error: 503.5091
Epoch 391/500
5/5 [==============================] - 0s 12ms/step - loss: 77.2332 - mean_squared_error: 72.9338 - val_loss: 526.6813 - val_mean_squared_error: 526.6813
Epoch 392/500
5/5 [==============================] - 0s 10ms/step - loss: 76.6113 - mean_squared_error: 77.1999 - val_loss: 545.6243 - val_mean_squared_error: 54

Epoch 436/500
5/5 [==============================] - 0s 10ms/step - loss: 66.8213 - mean_squared_error: 74.6473 - val_loss: 479.6571 - val_mean_squared_error: 479.6571
Epoch 437/500
5/5 [==============================] - 0s 10ms/step - loss: 63.5605 - mean_squared_error: 57.8140 - val_loss: 458.2617 - val_mean_squared_error: 458.2617
Epoch 438/500
5/5 [==============================] - 0s 10ms/step - loss: 69.2286 - mean_squared_error: 79.2507 - val_loss: 481.7897 - val_mean_squared_error: 481.7897
Epoch 439/500
5/5 [==============================] - 0s 10ms/step - loss: 67.5753 - mean_squared_error: 65.8985 - val_loss: 399.3784 - val_mean_squared_error: 399.3784
Epoch 440/500
5/5 [==============================] - 0s 8ms/step - loss: 63.7988 - mean_squared_error: 61.4542 - val_loss: 471.2119 - val_mean_squared_error: 471.2119
Epoch 441/500
5/5 [==============================] - 0s 10ms/step - loss: 64.7486 - mean_squared_error: 63.6408 - val_loss: 488.4217 - val_mean_squared_error: 48

Epoch 485/500
5/5 [==============================] - 0s 11ms/step - loss: 49.2203 - mean_squared_error: 47.0467 - val_loss: 438.8188 - val_mean_squared_error: 438.8188
Epoch 486/500
5/5 [==============================] - 0s 9ms/step - loss: 48.0640 - mean_squared_error: 46.3142 - val_loss: 405.4080 - val_mean_squared_error: 405.4080
Epoch 487/500
5/5 [==============================] - 0s 8ms/step - loss: 47.5794 - mean_squared_error: 47.2979 - val_loss: 395.3594 - val_mean_squared_error: 395.3594
Epoch 488/500
5/5 [==============================] - 0s 10ms/step - loss: 48.5923 - mean_squared_error: 46.0655 - val_loss: 420.8207 - val_mean_squared_error: 420.8207
Epoch 489/500
5/5 [==============================] - 0s 10ms/step - loss: 47.4741 - mean_squared_error: 46.8763 - val_loss: 393.8763 - val_mean_squared_error: 393.8763
Epoch 490/500
5/5 [==============================] - 0s 9ms/step - loss: 46.4287 - mean_squared_error: 43.8727 - val_loss: 413.6591 - val_mean_squared_error: 413.